name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.work

      - name: setup re2 for cgo
        run: sudo apt-get update && sudo apt-get install -y libre2-dev

      - run: go run mage benchall

      - run: go run mage wafbenchall

      - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v3
        with:
          name: results
          path: build/*bench*.txt
