name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.yaml'
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5
        with:
          go-version-file: go.work
          cache-dependency-path: |
            **/go.sum
            magefiles/versions.go

      - name: setup re2 for cgo
        run: sudo apt-get update && sudo apt-get install -y libre2-dev

      - run: go run mage benchall

      - run: go run mage wafbenchall

      - uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097 # v3
        with:
          name: results
          path: build/*bench*.txt
